name: Jac_speech Tests

on:
  push:
    branches: [ main ]
    paths:
      - jaseci_ai_kit/jac_speech/**
  pull_request:
    branches: [ main ]
    paths:
      - jaseci_ai_kit/jac_speech/**
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set swap space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 5

    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsndfile1 ffmpeg
        sudo apt-get install -y espeak-ng
        python -m pip install --upgrade pip

    - name: Install jaseci_core
      run: |
        pip3 install jaseci_core/

    - name: Install jac_speech
      run: |
        cd jaseci_ai_kit/jac_speech
        pip install -e .[all]
        pip install TTS==0.12.0

    - name: Verify jac_speech installation
      run: |
        python -c "import jac_speech"

    - name: Run tests
      run: |
        cd jaseci_ai_kit/jac_speech
        source ../test.sh
