site_name: The Jac Programming Language
site_url: https://jac-lang.org
nav:
  - Home: "index.md"
  - Start:
      - "start/about.md"
      - "start.md"
      - "start/installation.md"
      - "start/jac_in_a_flash.md"
  - Learn:
      - For coders:
          - "learn/guide.md"
          - "learn/jac_ref.md"
          - "learn/impl_docs.md"
          - Data Spatial:
              - "learn/data_spatial/examples.md"
              - "learn/data_spatial/sequence.md"
              - "learn/data_spatial/FAQ.md"
          - Jac Cloud:
              - "learn/coders/jac-cloud/docs/jac_cloud.md"
              - "learn/coders/jac-cloud/docs/permission.md"
              - "learn/coders/jac-cloud/docs/jac_cloud_logging.md"
              - "learn/coders/jac-cloud/docs/jac_cloud_env_vars.md"
              - "learn/coders/jac-cloud/docs/jac_cloud_webhook.md"
          - MTLLM:
              - "learn/with_llm.md"
              - Quick Start:
                  - "learn/coders/mtllm/docs/quickstart/installation.md"
                  - "learn/coders/mtllm//docs/quickstart/minimal-working-example.md"
              - Design and Implementation:
                  - "learn/coders/mtllm/docs/design_impl/inference_engine.md"
                  - "learn/coders/mtllm/docs/design_impl/sem_registry.md"
              - Building Blocks:
                  - "learn/coders/mtllm/docs/building_blocks/language_models.md"
                  - "learn/coders/mtllm/docs/building_blocks/semstrings.md"
                  - "learn/coders/mtllm/docs/building_blocks/functions_methods.md"
                  - "learn/coders/mtllm/docs/building_blocks/object_init.md"
                  - "learn/coders/mtllm/docs/building_blocks/Multimodality.md"
              - Tutorials:
                  - "learn/coders/mtllm/docs/tutorials/rpg_game.md"
          - "learn/tips_tricks.md"
          - "learn/jac_plugins.md"
      - For contributors:
          - "learn/contrib.md"
          - "learn/internals.md"
      - W.I.P:
          - "learn/ast_doc.md"
          - projects:
              - "projects/auto_ref.md"

  - Why: "why.md"
  # - ~/roadmap$: 'roadmap.md'
  - Github: https://github.com/Jaseci-Labs/jaseci

  - EECS449:
      - "learn/tutorial/readme.md"
      - "learn/tutorial/1_setting-up-jac-cloud.md"
      - "learn/tutorial/2_building-a-rag-chatbot.md"
      - "learn/tutorial/3_rag-dialogue-routing-chatbot.md"
theme:
  logo: "assets/logo.png"
  name: "material"
  palette:
    scheme: "slate"
    primary: "black"
    accent: "orange"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.footer
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: material/fire
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      pygments_style: "autumn"
  - pymdownx.inlinehilite
  # - codehilite:
  #     linenums: true
  - pymdownx.snippets:
      base_path: [".", "../../"]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
copyright: Copyright &copy; 2023 - 2024 Jac Hackers Everwhere

plugins:
  - search
  - open-in-new-tab
