site_name: The Jac Programming Language
site_url: https://jac-lang.org
nav:
    - ~$: 'index.md'
    # - ~/tour$: 'tour.md'
    # - ~/example$: 'example.md'
    - ~/start$: 'start.md'
    - ~/learn$:
      - 'learn/learn.md'
      - ~/for_coders:
        - 'learn/coders/no_indent.md'
        - 'learn/coders/defs_decls.md'
      - ~/for_noobs:
        - 'learn/contrib.md'
      - ~/for_contributors:
        - 'learn/contrib.md'
      - ~/w.i.p$:
        - 'learn/py_to_jac_example.md'
        - 'learn/ast_doc.md'
        - ~/book$:
          - book/main.md
          - book/general.md
          - book/blue.md
          - book/purple.md
          - book/red.md

    - ~/why$: 'why.md'
    - ~/roadmap$: 'roadmap.md'
    - ~/github$: https://github.com/Jaseci-Labs/jaclang

theme:
    logo: 'assets/logo.png'
    name: 'material'
    palette:
        scheme: 'slate'
        primary: 'black'
        accent: 'orange'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      pygments_style: 'autumn'
  - pymdownx.inlinehilite
  # - codehilite:
  #     linenums: true
  - pymdownx.snippets:
      base_path: ['.', '../../']
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
copyright: Copyright &copy; 2023 - 20XX Jac Hackers Everwhere

plugins:
  - search
  - open-in-new-tab