apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jaseci.fullname" . }}-up
data:
  prod_up: |
{{ .Files.Get .Values.configMap.filename | indent 4 }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jaseci.fullname" . }}-redis-config
data:
  redis-config: |
{{ .Values.configMap.redis.maxmemory | indent 4 }}
{{ .Values.configMap.redis.maxmemorypolicy | indent 4 }}