# Default values for jaseci.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: python:3-slim
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  db:
    repository: postgres:alpine
    port: 5432
    storage: 10Gi
  redis:
    repository: redis
    command:
      - redis-server
      - "/redis-master/redis.conf"
    port: 6379
  jasecikit: jaseci/jaseci-kit:latest

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: false


configMap:
  filename: dev_up
  redis:
    maxmemory: maxmemory 1000mb
    maxmemorypolicy: maxmemory-policy allkeys-lru

volumeMount:
  name: prod-script
  mountPath: /script
  db:
    mountPath: /var/lib/postgresql/data

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: 
   requests:
     memory: 350Mi

redis:
  resources:
    limits:
      cpu: "0.2"


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

#Ai Model to Deploy

aimodels:      
  - name: js-use-enc
    script:
      - pip install jaseci-kit==1.3.3.19
      - uvicorn jaseci_kit.use_enc:serv_actions --host 0.0.0.0 --port 80
    resources: 
      requests:
          memory: 1Gi
      limits:
          memory: 1Gi
  - name: js-use-qa
    script:
      - pip install jaseci-kit==1.3.3.19
      - uvicorn jaseci_kit.use_qa:serv_actions --host 0.0.0.0 --port 80    
    resources: 
      requests:
          memory: 1Gi
      limits:
          memory: 1Gi

  - name: summarization
    script:
      - git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
      - cd /jaseci/jaseci_core/
      - source install.sh
      - cd /jaseci
      - cd /jaseci/jaseci_kit/jaseci_kit/modules/summarization
      - uvicorn summarization:serv_actions --host 0.0.0.0 --port 80  
    resources: 
      requests:
          memory: 1Gi
      limits:
          memory: 1Gi


