name: jaseci_ai_kit Tests

on:
  push:
    branches: [ main ]
    paths:
      - jaseci_ai_kit/**
  pull_request:
    branches: [ main ]
    paths:
      - jaseci_ai_kit/**

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set swap space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 5

    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt -y upgrade
        sudo apt -y install --no-install-recommends git g++ build-essential pkg-config cmake
        sudo apt-get install -y libsndfile1 ffmpeg
        sudo apt-get install espeak-ng
        python -m pip install --upgrade pip
        pip install TTS

    - name: Install jaseci_core
      run: |
        pip3 install jaseci_core/

    - name: Install jaseci_ai_kit
      run: |
        pip3 install jaseci_ai_kit/

    - name: Verify jaseci_ai_kit installation
      run: |
        python -c "import jaseci_ai_kit"

    - name: Run tests
      run: |
        cd jaseci_ai_kit/
        source test.sh
