name: Run tests for jac-cloud

on:
  pull_request:
    paths:
      - "jac-cloud/**"
  push:
    branches:
      - main
    paths:
      - "jac-cloud/**"

jobs:
  test-cloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jac-cloud
    env:
      SHOW_ENDPOINT_RETURNS: true
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-replica-set: test-rs

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd ../jac
          pip install -e .
          cd ../jac-cloud
          pip install -e .
          pip install pytest

      - name: Run tests without mongodb and redis
        run: pytest -sx
      - name: Run tests with mongodb and redis
        run: pytest -sx
        env:
          SHOW_ENDPOINT_RETURNS: true
          DATABASE_HOST: mongodb://localhost/?retryWrites=true&w=majority
          REDIS_HOST: redis://localhost
