name: Run tests for jac-mtllm

on:
  pull_request:
    paths:
      - "jac-mtllm/**"
  push:
    branches:
      - main
    paths:
      - "jac-mtllm/**"

jobs:
  test-mtllm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jac-mtllm
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest opencv-python-headless pillow

    - name: Run tests
      run: pytest -x
